#!/usr/bin/env bash
# Configures a new Ubuntu machine to have a custom 404 page that contains the string Ceci n'est pas une page
apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
service nginx restart
