#!/usr/bin/env bash
# SSH client configuration to use private key ~/.ssh/school and refuse to authenticate using a password
Host *
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
